### ISSUE TITLE
footer line not in position in new hiker form    

### ISSUE THREAD

**Issue by budhasanjeev** [sanjeevbudhamagar/HIMS#1]
![screenshot from 2016-05-29 16-53-30](https://cloud.githubusercontent.com/assets/9959201/15632859/4c6bb10c-25be-11e6-82e8-1f1ba9a7f586.png)

**Comment by anijorshrestha** [comment]
![solved](https://cloud.githubusercontent.com/assets/17874752/15643940/bc6ae606-266f-11e6-8d4c-9ee2114301f2.PNG)

Problem solved
